

SET LANGUAGE 'us_english'
GO

select * from cliente

select * from IMOVEL

CREATE DATABASE Imobiliaria

CREATE TABLE CLIENTE(
	COD_CLIENTE INT PRIMARY KEY IDENTITY ,
	NOME VARCHAR (25) NOT NULL,
	SOBRENOME VARCHAR (40) NOT NULL,
	EMAIL VARCHAR (50) NOT NULL,
	SENHA VARCHAR (15) NOT NULL)
	
	
CREATE TABLE IMOVEL(
	COD_IMOVEL INT PRIMARY KEY IDENTITY ,
	TIPO_CONTRATO VARCHAR (7) NOT NULL,
	TIPO_IMOVEL VARCHAR (11) NOT NULL,
	NUMERO_COMODOS INT,
	AREA_TERRENO INT,
	PREÇO MONEY NOT NULL,
	DESCRICAO VARCHAR (200),
	SITUACAO VARCHAR (10),
	DATA_INCLUSAO DATETIME)
	
	
CREATE TABLE CORRETOR(	
	COD_CORRETOR INT PRIMARY KEY IDENTITY ,
	NOME VARCHAR (25) NOT NULL,
	SOBRENOME VARCHAR (40) NOT NULL,
	EMAIL VARCHAR (50) NOT NULL,
	SENHA VARCHAR (15) NOT NULL,
	COMISSAO INT)
	
	
	
INSERT INTO CLIENTE VALUES ('ROGERIO' , 'TROVIJO' , 'rogerio.trovijo@fatec.sp.gov.br' , '123456')

INSERT INTO IMOVEL VALUES ('COMPRA' , 'CASA' , 5 , '' , 100000 , 'IMOVEL NOVO EM INDAIATUBA' , 'VENDIDO',GETDATE())

INSERT INTO IMOVEL VALUES ('ALUGUEL' , 'APARTAMENTO' , 4 , '' , 1200 , 'VALOR DO CONDOMINIO R$ 250,00 NÃO INCLUSO' , 'ALUGADO',GETDATE())

INSERT INTO IMOVEL VALUES ('COMPRA' , 'TERRENO' , '' , 300 , 150000 , 'TERRENO EM ÓTIMA LOCALIZAÇÃO DA CIDADE' ,'DISPONIVEL', GETDATE())

INSERT INTO IMOVEL VALUES ('COMPRA' , 'CHACARA' , '' , 2000 , 450000 , 'CHACARA COM POMAR FORMADO' , 'DISPONIVEL',GETDATE())

INSERT INTO IMOVEL VALUES ('ALUGUEL' , 'COMERCIAL' , 10 , '' , 5000 , 'GALPÃO NO DISTRITO INDUSTRIAL' ,'ALUGADO', GETDATE())

INSERT INTO IMOVEL VALUES ('ALUGUEL' , 'COMERCIAL' , 10 , '' , 1000 , 'GALPÃO ' ,'DISPONIVEL', GETDATE())
	
	

CREATE PROC SIT_IMOVEL @SIT VARCHAR(10)
AS

BEGIN TRY

SELECT * FROM IMOVEL WHERE SITUACAO = @SIT

END TRY

BEGIN CATCH
IF @@ERROR <> 0
BEGIN
RAISERROR('Ocorreu um erro na procura do Imóvel',15,1);
RETURN
END
END CATCH


EXEC SIT_IMOVEL 'DISPONIVEL'


ALTER TRIGGER ALTERA_VALOR 
ON IMOVEL
FOR UPDATE
AS

DECLARE @COD INT
DECLARE @VALOR MONEY 
DECLARE @TIPO VARCHAR (11)
DECLARE @SITUACAO VARCHAR (10)

IF UPDATE (PREÇO)

BEGIN

SELECT @COD = COD_IMOVEL, @VALOR = PREÇO, @TIPO = TIPO_CONTRATO, @SITUACAO = SITUACAO FROM INSERTED

IF @VALOR > 2000 AND @TIPO = 'ALUGUEL' AND @SITUACAO = 'DISPONIVEL'
	BEGIN
		UPDATE IMOVEL
		SET PREÇO = @VALOR * 0.9
		WHERE COD_IMOVEL = @COD
	END
	
END

UPDATE IMOVEL SET PREÇO = 3000, SITUACAO = 'ALUGADO' WHERE COD_IMOVEL = 2

SELECT * FROM IMOVEL













	
	
	

